source 'https://rubygems.org'
ruby '2.3.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Use Material Design Icons
gem 'material_icons'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Use font awesome for social media icons
gem 'font-awesome-rails'

gem 'devise', '~> 4.2.0'

gem 'figaro', '~> 1.1'

gem 'uglifier', '~> 3.0'

gem 'money-rails', '~> 1.7'

gem 'sprockets-rails'
# Use paperclip for file uploads
gem 'paperclip'
# Use aws-sdk to allow paperclip to upload to s3
gem 'aws-sdk', '~> 2.7', '>= 2.7.7'
# Use filterrific for easier filtering on admin panel
gem 'filterrific', '~> 2.1'
# Use will_paginate for easier pagination
gem 'will_paginate', '~> 3.1'

gem 'pg_search'

gem 'ffaker'

gem 'momentjs-rails'

gem 'chart-js-rails'

gem 'newrelic_rpm'

gem 'stripe', '~> 2.2'

gem 'sidekiq'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger
  # console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %>
  # anywhere in the code.
  gem 'listen', '~> 3.0.5'
  gem 'web-console'
  # Spring speeds up development by keeping your application running in the
  # background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # Add better errors
  # gem "better_errors"
  # gem "binding_of_caller"
end

group :production do
  gem 'rails_12factor'
end
